print('Cadastro de endereço')
rua = input('Rua: ')
num = input('Nº: ')
bairro = input('Bairro: ')
cidade = input('Cidade: ')
uf = input('UF: ')
cep = input('Cep: ')
print('Endereço:')
print('Rua:', rua, 'Nº:', num, 'Bairro:', bairro, '\nCidade:', cidade, 'UF:', uf, 'Cep:', cep)