print('Cadastro de endereço')
rua = input('Rua: ')
numero = input('N°: ')
bairro = input('Bairro: ')
cidade = input('Cidade: ')
uf = input('UF: ')
cep = input('Cep: ')
print('Endereço: ')
print('Rua: ', rua, 'N°: ', 'Bairro: ', bairro)
print('Cidade: ', cidade, 'UF: ', uf, 'Cep: ', cep)